mytardis:
    base: https://foo.bar
    username: username
    password: password

hcp:
    host: s3.some-region.amazonaws.com
    base: ""
    access: some-access-key-from-amazon-iam
    secret: some-secret-key-from-amazon-iam
    bucket: some-bucket-name-from-amazon-s3
